name: ServerlessChat-Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: ServerlessChat-Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.801'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g serverless
      - name: Build and Deploy Serverless.Chat
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: ./build-and-deploy-serverless-chat.sh